ansible_user: ec2-user
ansible_password: DevOps321

MONGODB_HOST: mongodb-{{ env }}.daws88s.shop
REDIS_HOST: redis-{{ env }}.daws88s.shop
CART_HOST: cart.backend-alb-{{ env }}.daws88s.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws88s.shop
MYSQL_HOST: mysql-{{ env }}.daws88s.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.daws88s.shop
USER_HOST: user.backend-alb-{{ env }}.daws88s.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws88s.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws88s.shop
#catalogue.backend-alb-sbx.daws88s.shop
#mongodb-sbx.daws88s.shop