- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

- name: Authenticatio and Import required databases
  community.mysql.mysql_db:
    login_user: root
    login_host: "{{ MYSQL_HOST }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    state: import
    name: all
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml
